credentials:
  usernames:
    edomarcolab2:
      email: edomarcolab2@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: edomarcolab2
      password: abc # Will be hashed automatically
    edoardomarchetti2:
      email: edoardomarchetti2@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Edoardo Marchetti
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - edoardomarchetti2@gmail.com